branch-defaults:
  main:
    environment: trufkelarx-env
    group_suffix: null
global:
  application_name: trufkelarx
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 22
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
